apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-mhjp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-mhjp
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-mhjp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-mhjp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-mhjp
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lhzg-tenant/rhtap-demo-app/hacbs-test-project-mhjp@sha256:f74cee5efdab736e9e09f93dd6f8df943154f8b711f6250a879a1473c2841f2c
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
