apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-mhjp
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lhzg-tenant/rhtap-demo-app/hacbs-test-project-mhjp@sha256:05d98b64b5a2ecda42f5da37f28cbd57272120c350f06b077d80ff0cba5a693c
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
