apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-mhjp
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lhzg-tenant/rhtap-demo-app/hacbs-test-project-mhjp@sha256:f74cee5efdab736e9e09f93dd6f8df943154f8b711f6250a879a1473c2841f2c
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
